global:
    api-listen-addr: :5183
    timeout: 10s
    memo: "Marsel | Stake-Take#3344"
    light-cache-size: 20
default_chain: stride
chains:
    gaia:
            key: Marsel1
            chain-id: GAIA
            rpc-addr: http://stride.stake-take.com:46657
            grpc_addr: http://stride.stake-take.com:9490
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.3
            gas-prices: 0.01uatom
            key-directory: $HOME/.icq/keys
            debug: true
            timeout: 10s
            output-format: json
            sign-mode: sync
            strategy:
            type: native
            order: UNORDERED
    stride:
            key: Marsel2
            chain-id: STRIDE-TESTNET-2
            rpc-addr: http://stride.stake-take.com:26657
            grpc_addr: http://stride.stake-take.com:9090
            account-prefix: stride
            keyring-backend: test
            gas-adjustment: 1.3
            gas-prices: 0.01ustrd
            key-directory: $HOME/.icq/keys
            debug: true
            timeout: 20s
            output-format: json
            sign-mode: sync
            strategy:
            type: native
            order: UNORDERED
cl: {}
